version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=loan_risk_db
    depends_on:
      - db

  dashboard:
    build: .
    command: streamlit run app/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: loan_risk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pgdata:
